language: java

sudo: false
cache:
  directories:
      - $HOME/.m2

dist: trusty
before_script:
  - jdk_switcher use $JDK

script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn clean install $PHASE | egrep -v 'Download|Install'; [ ${PIPESTATUS[0]} == 0 ]; fi
# Remove --quiet to avoid timeouts
install: mvn -U install -DskipTests=true | egrep -v 'Download|Install'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"

matrix:
  include:
    - env: PHASE="-Ptravis-nodb,jdk16" JDK=oraclejdk8
    - env: PHASE="-Ptravis-nodb,jdk16" JDK=openjdk8
    - env: PHASE="-Ptravis-nodb,jdk17" JDK=oraclejdk8
    - env: PHASE="-Ptravis-nodb,jdk17" JDK=openjdk8
    - env: PHASE="-Ptravis-nodb,jdk18" JDK=oraclejdk8
    - env: PHASE="-Ptravis-nodb,jdk18" JDK=openjdk8
  fast_finish: true

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml && travis_wait mvn deploy -DskipTests=true --settings ~/settings.xml | egrep -v "Download|Install|Upload" ; rm -f ~/settings.xml'
