language: java
script: mvn clean install -Ptravis-nodb
# Remove --quiet to avoid timeouts
install: mvn install -DskipTests=true

notifications:
  email:
    - kill-bill-commits@googlegroups.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

env:
  - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml && mvn deploy --settings ~/settings.xml ; rm -f ~/settings.xml'
